# Generated by Django 4.2.26 on 2025-11-21 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPurchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否选择采购')),
                ('bidding_status', models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('successful', '竞标成功'), ('failed', '竞标失败'), ('cancelled', '已取消')], default='not_started', max_length=20, verbose_name='竞标状态')),
                ('client_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='甲方联系人')),
                ('client_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='甲方联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_info', to='emall.procurementemall')),
            ],
            options={
                'verbose_name': '采购进度管理',
                'verbose_name_plural': '采购进度管理',
                'db_table': 'procurement_purchasing',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='供应商名称')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='获取渠道')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系方式')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='店铺名称')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'procurement_suppliers',
            },
        ),
        migrations.CreateModel(
            name='SupplierCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='商品规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='价格')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('product_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='产品链接')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodities', to='emall_purchasing.supplier')),
            ],
            options={
                'verbose_name': '供应商商品',
                'verbose_name_plural': '供应商商品',
                'db_table': 'supplier_commodities',
            },
        ),
        migrations.CreateModel(
            name='ProcurementSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否选择该供应商')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emall_purchasing.procurementpurchasing')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emall_purchasing.supplier')),
            ],
            options={
                'verbose_name': '采购供应商关系',
                'verbose_name_plural': '采购供应商关系',
                'db_table': 'procurement_supplier_relation',
                'unique_together': {('procurement', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='ProcurementRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_content', models.TextField(verbose_name='备注内容')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_history', to='emall_purchasing.procurementpurchasing')),
            ],
            options={
                'verbose_name': '采购备注记录',
                'verbose_name_plural': '采购备注记录',
                'db_table': 'procurement_purchasing_remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='suppliers',
            field=models.ManyToManyField(related_name='procurements', through='emall_purchasing.ProcurementSupplier', to='emall_purchasing.supplier'),
        ),
    ]
