# Generated by Django 4.2.26 on 2025-11-21 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementPurchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_selected', models.BooleanField(default=False, verbose_name='是否选择采购')),
                ('client_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='甲方联系人')),
                ('client_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='甲方联系方式')),
                ('supplier_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商获取渠道')),
                ('supplier_store', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商店铺名称')),
                ('supplier_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商联系方式')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='成本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_info', to='emall.procurementemall')),
            ],
            options={
                'verbose_name': '采购进度管理',
                'verbose_name_plural': '采购进度管理',
                'db_table': 'procurement_purchasing',
            },
        ),
    ]
