# Generated by Django 4.2.26 on 2025-11-21 06:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementpurchasing',
            name='bidding_status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('successful', '竞标成功'), ('failed', '竞标失败'), ('cancelled', '已取消')], default='not_started', max_length=20, verbose_name='竞标状态'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='commodity_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None, verbose_name='商品名'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='prices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True), blank=True, null=True, size=None, verbose_name='价格'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='product_specifications',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), blank=True, null=True, size=None, verbose_name='产品规格'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='product_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=500), blank=True, null=True, size=None, verbose_name='产品链接'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='quantities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='备注说明'),
        ),
    ]
