# Generated by Django 4.2.26 on 2025-11-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0001_initial'),
    ]

    operations = [
    ]
