# Generated by Django 4.2.26 on 2025-11-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0002_auto_20251121_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementremark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
