# Generated by Django 4.2.26 on 2025-11-21 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0002_procurementpurchasing_bidding_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_content', models.TextField(verbose_name='备注内容')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks_history', to='emall_purchasing.procurementpurchasing')),
            ],
            options={
                'verbose_name': '采购备注记录',
                'verbose_name_plural': '采购备注记录',
                'db_table': 'procurement_purchasing_remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
