# Generated by Django 4.2.26 on 2025-11-30 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0003_procurementremark_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementpurchasing',
            name='client_contact',
        ),
        migrations.RemoveField(
            model_name='procurementpurchasing',
            name='client_phone',
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='联系人姓名')),
                ('contact_info', models.CharField(max_length=255, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_contacts', to='emall_purchasing.procurementpurchasing')),
            ],
            options={
                'verbose_name': '甲方联系人',
                'verbose_name_plural': '甲方联系人',
                'db_table': 'procurement_client_contacts',
            },
        ),
    ]
