# Generated by Django 4.2.26 on 2025-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0004_remove_procurementpurchasing_client_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementpurchasing',
            name='project_owner',
            field=models.CharField(blank=True, default='未分配', max_length=100, null=True, verbose_name='项目归属人'),
        ),
    ]
