# Generated by Django 4.2.26 on 2025-12-01 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emall', '0001_initial'),
        ('emall_purchasing', '0005_procurementpurchasing_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedProcurementRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_content', models.TextField(verbose_name='备注内容')),
                ('created_by', models.CharField(max_length=100, verbose_name='创建人')),
                ('remark_type', models.CharField(choices=[('general', '普通备注'), ('purchasing', '采购进度备注'), ('client', '客户沟通备注')], default='general', max_length=20, verbose_name='备注类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_remarks', to='emall.procurementemall')),
                ('purchasing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_remarks', to='emall_purchasing.procurementpurchasing')),
            ],
            options={
                'verbose_name': '统一采购备注',
                'verbose_name_plural': '统一采购备注',
                'db_table': 'unified_procurement_remarks',
                'ordering': ['-created_at'],
            },
        ),
    ]
