# Generated by Django 4.2.26 on 2025-12-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0006_unifiedprocurementremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementpurchasing',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='选择时间'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='unselected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消选择时间'),
        ),
    ]
