# Generated by Django 4.2.26 on 2025-12-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0007_procurementpurchasing_selected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementsupplier',
            name='purchaser_created_by',
            field=models.CharField(default='未知用户', max_length=100, verbose_name='采购创建人'),
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='purchaser_created_role',
            field=models.CharField(default='unassigned', max_length=20, verbose_name='采购创建人角色'),
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='purchaser_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购更新人'),
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='purchaser_updated_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='采购更新人角色'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchaser_created_by',
            field=models.CharField(default='未知用户', max_length=100, verbose_name='采购创建人'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchaser_created_role',
            field=models.CharField(default='unassigned', max_length=20, verbose_name='采购创建人角色'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchaser_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购更新人'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchaser_updated_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='采购更新人角色'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='purchaser_created_by',
            field=models.CharField(default='未知用户', max_length=100, verbose_name='采购创建人'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='purchaser_created_role',
            field=models.CharField(default='unassigned', max_length=20, verbose_name='采购创建人角色'),
        ),
        migrations.AlterField(
            model_name='suppliercommodity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='商品名稱'),
        ),
    ]
