# Generated by Django 4.2.26 on 2025-12-08 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0008_procurementsupplier_purchaser_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementsupplier',
            name='purchaser_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='采购创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='purchaser_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='采购更新时间'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchaser_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='采购创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='purchaser_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='采购更新时间'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='purchaser_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='采购创建时间'),
            preserve_default=False,
        ),
    ]
