# Generated by Django 4.2.26 on 2025-12-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0009_procurementsupplier_purchaser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementsupplier',
            name='final_negotiated_quote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='最终协商报价'),
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='final_quote_modified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最终报价修改时间'),
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='final_quote_modified_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='最终报价修改人'),
        ),
        migrations.AddField(
            model_name='procurementsupplier',
            name='final_quote_modified_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='最终报价修改人角色'),
        ),
    ]
