# Generated by Django 4.2.26 on 2025-12-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0010_procurementsupplier_final_negotiated_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliercommodity',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='支付金额'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='物流单号'),
        ),
    ]
