# Generated by Django 4.2.26 on 2025-12-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0011_suppliercommodity_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('changed_by', models.CharField(max_length=100, verbose_name='操作人')),
                ('changed_role', models.CharField(max_length=20, verbose_name='操作人角色')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_audits', to='emall_purchasing.suppliercommodity')),
            ],
            options={
                'verbose_name': '支付金额审计',
                'verbose_name_plural': '支付金额审计',
                'db_table': 'payment_audit_log',
            },
        ),
        migrations.CreateModel(
            name='LogisticsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_by', models.CharField(max_length=100, verbose_name='操作人')),
                ('changed_role', models.CharField(max_length=20, verbose_name='操作人角色')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_audits', to='emall_purchasing.suppliercommodity')),
            ],
            options={
                'verbose_name': '物流单号审计',
                'verbose_name_plural': '物流单号审计',
                'db_table': 'logistics_audit_log',
            },
        ),
    ]
