# Generated by Django 4.2.26 on 2025-12-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0012_paymentauditlog_logisticsauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementpurchasing',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='结算金额'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='结算日期'),
        ),
        migrations.AddField(
            model_name='procurementpurchasing',
            name='winning_date',
            field=models.DateField(blank=True, null=True, verbose_name='中标日期'),
        ),
    ]
