# Generated by Django 4.2.26 on 2025-12-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0013_procurementpurchasing_settlement_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontact',
            name='purchaser_created_by',
            field=models.CharField(default='未知用户', max_length=100, verbose_name='采购创建人'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='purchaser_created_role',
            field=models.CharField(default='unassigned', max_length=20, verbose_name='采购创建人角色'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='purchaser_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='采购更新时间'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='purchaser_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购更新人'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='purchaser_updated_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='采购更新人角色'),
        ),
        migrations.AddField(
            model_name='procurementremark',
            name='created_role',
            field=models.CharField(default='unassigned', max_length=20, verbose_name='创建人角色'),
        ),
        migrations.AddField(
            model_name='procurementremark',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='procurementremark',
            name='updated_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='更新人角色'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='purchaser_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='采购更新时间'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='purchaser_updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='采购更新人'),
        ),
        migrations.AddField(
            model_name='suppliercommodity',
            name='purchaser_updated_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='采购更新人角色'),
        ),
        migrations.AddField(
            model_name='unifiedprocurementremark',
            name='created_role',
            field=models.CharField(default='unassigned', max_length=20, verbose_name='创建人角色'),
        ),
        migrations.AddField(
            model_name='unifiedprocurementremark',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='unifiedprocurementremark',
            name='updated_role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='更新人角色'),
        ),
    ]
