# Generated by Django 6.0.1 on 2026-02-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emall_purchasing', '0014_clientcontact_purchaser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercommodity',
            name='product_url',
            field=models.TextField(blank=True, null=True, verbose_name='产品链接'),
        ),
    ]
