# Generated by Django 6.0.1 on 2026-02-05 10:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementEmall',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fp_total_price_control', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_publish_date', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_purchasing_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_project_number', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_quote_start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_quote_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_region', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fp_commodity_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_parameter_requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_purchase_quantities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_control_amounts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_suggested_brands', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_business_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_business_requirements', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_related_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
                ('fp_download_files', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True)),
            ],
            options={
                'db_table': 'procurement_fp_emall',
                'managed': False,
            },
        ),
    ]
