# Generated by Django 6.0.1 on 2026-02-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='展示标题')),
                ('province', models.CharField(choices=[('JX', '江西'), ('HN', '湖南'), ('AH', '安徽'), ('ZJ', '浙江')], db_index=True, max_length=10)),
                ('root_category', models.CharField(choices=[('goods', '物资'), ('service', '服务'), ('project', '工程')], db_index=True, max_length=20)),
                ('sub_category', models.CharField(blank=True, choices=[('office', '行政办公耗材'), ('cleaning', '清洁日化用品'), ('digital', '数码家电'), ('sports', '体育器材与服装'), ('industrial', '专业设备与工业品'), ('food', '食品与饮品'), ('service_other', '服务与其他')], db_index=True, max_length=50, null=True)),
                ('mode', models.CharField(choices=[('bidding', '竞价'), ('reverse', '反拍')], db_index=True, default='bidding', max_length=20)),
                ('control_price', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.IntegerField(db_index=True, default=0)),
                ('source_emall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bidding_clean', to='emall.procurementemall', verbose_name='原始源')),
            ],
            options={
                'db_table': 'bidding_project_cleaned',
                'ordering': ['status', 'start_time'],
                'indexes': [models.Index(fields=['province', 'root_category', 'sub_category'], name='bidding_pro_provinc_25ce42_idx')],
            },
        ),
    ]
