# Generated by Django 6.0.1 on 2026-02-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
        ('emall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCommodityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField(blank=True, null=True, verbose_name='品牌ID')),
                ('item_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='商品名称')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='规格参数')),
                ('selected_suppliers', models.TextField(blank=True, null=True, verbose_name='推荐供应商JSON')),
                ('selection_reason', models.TextField(blank=True, null=True, verbose_name='推荐理由')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='使用的AI模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('procurement', models.ForeignKey(db_column='procurement_id', on_delete=django.db.models.deletion.CASCADE, related_name='commodity_results_bidding', to='emall.procurementemall', verbose_name='关联采购项目')),
            ],
            options={
                'verbose_name': 'AI寻源结果',
                'verbose_name_plural': 'AI寻源结果',
                'db_table': 'procurement_commodity_result',
            },
        ),
    ]
