# Generated by Django 6.0.1 on 2026-02-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_procurementcommodityresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementCommodityBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500, null=True, verbose_name='物品名称')),
                ('specifications', models.TextField(null=True, verbose_name='规格参数')),
                ('suggested_brand', models.CharField(max_length=500, null=True, verbose_name='建议品牌')),
                ('quantity', models.CharField(max_length=100, null=True, verbose_name='数量')),
                ('unit', models.CharField(max_length=50, null=True, verbose_name='单位')),
            ],
            options={
                'db_table': 'procurement_commodity_brand',
                'managed': False,
            },
        ),
    ]
