# Generated by Django 6.0.1 on 2026-02-05 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_procurementcommoditybrand'),
        ('emall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementcommodityresult',
            options={},
        ),
        migrations.RemoveField(
            model_name='biddingproject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='procurementcommodityresult',
            name='procurement',
        ),
        migrations.AddField(
            model_name='procurementcommodityresult',
            name='procurement_id',
            field=models.CharField(db_column='procurement_id', db_index=True, default='0', max_length=100, verbose_name='原始采购ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biddingproject',
            name='source_emall',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='bidding_clean', serialize=False, to='emall.procurementemall', verbose_name='原始源'),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='对应清单ID'),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='item_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='model_used',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='selected_suppliers',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='selection_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='procurementcommodityresult',
            name='specifications',
            field=models.TextField(null=True),
        ),
    ]
