# Generated by Django 4.2.26 on 2026-02-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_alter_procurementcommodityresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcommodityresult',
            name='status',
            field=models.CharField(default='completed', max_length=20, null=True),
        ),
    ]
