# Generated by Django 4.2.26 on 2025-12-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('unassigned', '未分配角色'), ('admin', '管理员'), ('procurement_staff', '采购人员'), ('supplier_manager', '供应商管理员')], default='unassigned', max_length=20),
        ),
    ]
