# Generated by Django 4.2.26 on 2025-12-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_count', models.IntegerField(default=0)),
                ('week_count', models.IntegerField(default=0)),
                ('month_count', models.IntegerField(default=0)),
                ('quarter_count', models.IntegerField(default=0)),
                ('year_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
