# Generated by Django 6.0.1 on 2026-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_dailyprofitstats_procurementstatusstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statistics_month', models.CharField(max_length=7)),
                ('project_count', models.IntegerField()),
                ('total_response_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_profit_margin', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('settlement_fund_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('avg_bid_cycle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_settlement_cycle', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectProfitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('project_status', models.CharField(max_length=50)),
                ('project_owner', models.CharField(max_length=100)),
                ('expected_total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('response_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('winning_date', models.DateTimeField(blank=True, null=True)),
                ('settlement_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('final_quote', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('purchase_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('procurement_id', models.IntegerField()),
                ('project_number', models.CharField(max_length=255)),
                ('bid_cycle_days', models.IntegerField(default=0)),
                ('settlement_cycle_days', models.IntegerField(default=0)),
                ('project_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project_profit_margin', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('statistics_month', models.CharField(max_length=7)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
